### ISSUE TITLE
Small Syntax error on Installation Quickstart

### ISSUE THREAD

**Issue by gpimentelv** [theforeman/theforeman.org#1087]
On the Quickstart link

https://www.theforeman.org/manuals/1.17/quickstart_guide.html

Installation Options for:

- Debian 9 (Stretch)
- Ubuntu 16.04 (Xenial)

Enable the Foreman Repo, last line (4)

`wget -q https://deb.theforeman.org/pubkey.gpg -O- | apt-key add -`

**Only works if the second command on the pipe is issued with sudo**

`wget -q https://deb.theforeman.org/pubkey.gpg -O- | sudo apt-key add -`

**Comment by mmoll** [comment]
basically that would the true for more or less all of the commands we're using there...

**Comment by GregSutcliffe** [comment]
Perhaps it would be easier to document that we expect it to be run as root (which can be done via `sudo -i`) ?

**Comment by ekohl** [comment]
> Perhaps it would be easier to document that we expect it to be run as root (which can be done via sudo -i) ?

Sounds good, but often people miss something like that. The convention is to use `# command` in the shell but we should make sure that it can still be copy-pasted. Not every user is familiar with the convention.

**Comment by GregSutcliffe** [comment]
Fair enough. I can make the changes easily enough for the quickstart, should we do this for the Yum instructions too?

**Comment by ekohl** [comment]
That'd be good.

**Comment by GregSutcliffe** [comment]
Created #1108 to address this.
