### ISSUE TITLE
Manual Page: bs-docs-sidebar doesn't scroll with page

### ISSUE THREAD

**Issue by stbenjam** [theforeman/theforeman.org#109]
The bs-docs-sidebar doesn't scroll with the page.  I suppose that's intentional, but on my Macbook Air this results in the scrollbar going off the screen and being unable to navigate to longer sections of the document:

![image](https://f.cloud.github.com/assets/429763/1402894/65c8c36a-3ceb-11e3-893c-8391ae79e4db.png)

Ostensibly, the "affix" attribute is supposed to fix this, but this didn't work when I tried it myself, but admittedly, my web design skills peaked around the time the blink tag was fashionable.

The first answer on this stackoverflow thread looks like the right direction:

http://stackoverflow.com/questions/4340143/sidebar-that-follows-scroll-but-scrolls-self-if-taller-than-viewport

**Comment by domcleal** [comment]
@abenari could you look into this please?

**Comment by domcleal** [comment]
Should now be fixed, thanks for reporting it @stbenjam.
