### ISSUE TITLE
Strange navigation behaviour in api documentation

### ISSUE THREAD

**Issue by anomaly256** [theforeman/theforeman.org#1111]
Hi, trying to read your api documentation and navigating the website appears to be a bit broken.  If I click for example Hosts, then the link for POST /api/hosts to try to see the params needed, the page just reloads in place with no further information being exposed because it's just a heading anchor to the spot on the page you're already at.  I have to click the easy to miss  '>>>' on the very far right edge of the page to go any deeper.  In fact I did miss this for quite a while as did several colleagues as it's easy to not even see the >>> at all in your peripheral vision when looking at the big bold headings at the far left edge of the page and the sea of white in between.

I'm not sure why you decided to break the basic navigation paradigm with this approach.  It's really quite annoying and unintuitive to browse your api documentation this way.

**Comment by lzap** [comment]
Hey there, I am unable to reproduce, my page loads fine. E.g. from:

https://theforeman.org/api/1.17/index.html

when I click GET /audits I end up in:

https://theforeman.org/api/1.17/apidoc/v2/audits/index.html

loaded in iframe. This is old school HTML. If you want to improve, feel free - the docs are actually being generated from our codebase using https://github.com/Apipie/apipie-rails one of our sub-projects. @iNecas

**Comment by lzap** [comment]
Ok definitely issue for apipie project, feel free to open ticket there: https://github.com/Apipie/apipie-rails/issues

There are almost 150 issues however and only few developers, this needs more people.

**Comment by anomaly256** [comment]
Just to clarify, try to click on the 'Audits' heading first, then 'GET /audits' on the page that loads from there to repro.
The issue with this behaviour might be more apparent when sending a link to someone for a specific, larger class, like [https://theforeman.org/api/1.17/apidoc/v2/compute_resources.html](https://theforeman.org/api/1.17/apidoc/v2/compute_resources.html)
from there the links don't go any further they just move the page up and down

Anyway thanks for pointing me to the right place, if I get a minute I'll have a shot at fixing it and do a PR if it's not a specific design choice.
