### ISSUE TITLE
Foreman 1.21 manual has lots of references to `locations/organizations` being optional.

### ISSUE THREAD

**Issue by alexjfisher** [theforeman/theforeman.org#1313]
Outside of the release notes, locations and organizations are still referred to as optional.

Some examples...
> Roles can be also associated to Locations or Organizations if these are allowed.

> Organization-level parameters if organizations are enabled...

> --foreman-locations-enabled -> 'Enable locations?'

> If locations or organizations are enabled, these can be inferred from...

> If organizations/locations are enabled, you can assign multiple organizations/locations to your LDAP authentication sources.

**Comment by tbrisker** [comment]
I believe this has been resolved by https://github.com/theforeman/theforeman.org/commit/13d31b89e45992ad4651619443721dccbad7eb48
