### ISSUE TITLE
Initial credentials don't display upon install completion Katello 3.11 / Foreman 1.21.3 / CentOS 7.1810

### ISSUE THREAD

**Issue by thinkitdata** [theforeman/theforeman.org#1371]
I've performed 5 seperate installations and the initial login credentials have not displayed in any of them.  Fortunately they can be found in:
/etc/foreman-installer/scenarios.d/katello-answers.yaml
initial_admin_username
initial_admin_password

**Comment by lzap** [comment]
Hello, this is our documentation tracker. I believe you report a bug? Then use our redmine tracker, installer component perhaps. Or open discussion on discourse. THanks.

**Comment by ekohl** [comment]
https://projects.theforeman.org/issues/26745 is fixed in nightly, still needs cherry picks.
