### ISSUE TITLE
Broken links on https://docs.theforeman.org/web/

### ISSUE THREAD

**Issue by markgraf** [theforeman/theforeman.org#1655]
Just wanted to let you know that all the links to guides on [https://docs.theforeman.org/web/](https://docs.theforeman.org/web/) are broken.

E.g https://docs.theforeman.org/web/master/doc-Planning_Guide/index-foreman.html tells me:

> **Not Found**
> The requested URL /web/master/doc-Planning_Guide/index-foreman.html was not found on this server.

**Comment by lzap** [comment]
Hello, thanks. Is this still an issue? We have completely dropped the `/web` prefix now, everything should be cleaner-looking.

**Comment by markgraf** [comment]
All good!  Thanks for letting me know!
