### ISSUE TITLE
git warning because of a file

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/theforeman.org#1766]
Hi all!
I tried cloning the repository but had an issue with a file:

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'static/presentations/Evgeni_Golov-Katello_and_Ansible_for_automated_testing_and_releasing_of_packages.pdf'
  'static/presentations/evgeni_golov-katello_and_ansible_for_automated_testing_and_releasing_of_packages.pdf'
```

`git status` always reports a modified file:
```
	modified:   static/presentations/Evgeni_Golov-Katello_and_Ansible_for_automated_testing_and_releasing_of_packages.pdf
```

I was not even able to create an adaquate PR; so it would be fantastic if someone else could investigate this issue.

Thanks and stay safe.
Maximilian.

**Comment by ekohl** [comment]
Are you by any chance on Windows?

Edit: @evgeni mind taking a look since they're your slides?

**Comment by evgeni** [comment]
Heh, do we have two versions with different capitalization?

**Comment by evgeni** [comment]
And actually different content, cool... Me--

**Comment by maximiliankolb** [comment]
I'm running macOS, but I am unsure if my file system can handle such oddities. The question isn't just if it's allowed/works; but whether it should be used this way.

**Comment by evgeni** [comment]
Apple FS is also not case sensitive by default.

I'll rename the file later.

**Comment by lzap** [comment]
The worst file system on Earth. They say the new one is much better but I don't believe them.

**Comment by maximiliankolb** [comment]
Thanks everyone! 👍

**Comment by lzap** [comment]
Was just citing Linus: https://en.wikipedia.org/wiki/HFS_Plus#Criticisms :-)
