### ISSUE TITLE
Foreman manual 1.4 GCE notes

### ISSUE THREAD

**Issue by mobcdi** [theforeman/theforeman.org#179]
To avoid people making the same silly mistake enabling GCE as a compute resource can I suggest the documentation for 5.2.4 Google Compute Engine Notes be updated from
"Requires client e-mail address and p12 certificate file to access" 
to 
Requires client e-mail address of an authorised google cloud console client ID is entered in the new compute resource screen and the .p12 certificate file is stored on the foreman server in a location the foreman user account has permission to read

**Comment by GregSutcliffe** [comment]
Feel free to send a PR - for this repo, I think GitHub will even let you edit the file in the web browser, and do the PR for you automatically :)

**Comment by mobcdi** [comment]
Pull  #180 added
