### ISSUE TITLE
https://yum.theforeman.org/ has issues: Error 503 Backend is unhealthy

### ISSUE THREAD

**Issue by isms-core-project** [theforeman/theforeman.org#1868]
Hi Folks,
First let me thank you for the hard work.
I was about to setup Foreman with Katello but there seems to be an issue with the repo URL.
![image](https://user-images.githubusercontent.com/37223044/127778101-4b52db1b-ccfd-4844-98b0-67e95ba69f6b.png)
I wish you a great Sunday.
BR
GG

**Comment by ekohl** [comment]
Thanks for the report. I'm not sure what happened but the backed server was no longer responding. I rebooted and it appears to work again. Does it also work for you?

**Comment by isms-core-project** [comment]
Hi ekohl,
TY for the message and server reboot.
Repos and Tutorial Pages work again.
Just perfect, I can continue my Foreman/Ketello installation.
I wish you a great Sunday.
BR
GG
