### ISSUE TITLE
Rocky Linux client operating system with status "unknown 8.5"

### ISSUE THREAD

**Issue by Obie38** [theforeman/theforeman.org#1979]
Hi,

I have some strange behavior with rocky linux clients. I get status "unknown 8.5" in "operating system" column for Rocky Linux hosts.
Rocky Linux client seems to be not recognized by foreman 2.5.2.19‑1. I get "unknown 8.5" in "operating system" column (hosts view). When I check the facts, distribution.name is right ("Rocky Linux") on the server side and on the client side.

Anyone has an idea about that ?
Thanks :)

**Comment by melcorr** [comment]
Hey @Obie38 

This issues page is for issues related to our website. Would you mind please posting over here: https://community.theforeman.org/ - this is where we normally gather to discuss and troubleshoot together.

**Comment by Obie38** [comment]
Yes I will, sorry
