### ISSUE TITLE
Security page outdated / no CVE announcements anymore?

### ISSUE THREAD

**Issue by timdeluxe** [theforeman/theforeman.org#2044]
I tried to look up for security announcements and found this page https://github.com/theforeman/theforeman.org/blob/gh-pages/security.md (i also found the same page here: https://github.com/theforeman/theforeman.org/security/policy - is it actually really the identical page or was it just copied?)
However this is VERY outdated. The linked google group does not exist anymore and there is no CVE announcement since 2021 - did nothing security-wise happen since then?
Looks like the only replacement is https://community.theforeman.org/c/release-announcements/8 - however this is general release announcement, not security-only.

Is there anything i missed? If not there should be a hint, that no new security announcements are published there anymore and a link to the discourse channel should be made. If i did not miss anything i am open to raise a PR to fix it.

**Comment by evgeni** [comment]
> I tried to look up for security announcements and found this page https://github.com/theforeman/theforeman.org/blob/gh-pages/security.md

Technically, the correct page is https://theforeman.org/security.html -- but the one you mention is the source for it.

> (i also found the same page here: https://github.com/theforeman/theforeman.org/security/policy - is it actually really the identical page or was it just copied?)

Neither, that's just GitHub automatically rendering the above `security.md` as the policy for this repo, which is quite wrong but here we are.

> However this is VERY outdated. The linked google group does not exist anymore and there is no CVE announcement since 2021 - did nothing security-wise happen since then? Looks like the only replacement is https://community.theforeman.org/c/release-announcements/8 - however this is general release announcement, not security-only.

No, I think it's correct, we didn't do any security announcements since then.
The `foreman-announce` group is indeed obsolete and should be replaced with a link to community.theforeman.org or this very page?

@ekohl @ehelms opinions?

**Comment by ekohl** [comment]
> The `foreman-announce` group is indeed obsolete and should be replaced with a link to community.theforeman.org or this very page?

Probably both https://community.theforeman.org/c/release-announcements/8 and https://theforeman.org/security.html

**Comment by timdeluxe** [comment]
@evgeni Thanks for explaining and yes, i know that the page i found is the source for the security page on the website. It is more that i linked the "wrong" stuff, but i think you understood me.

@ekohl 
> ...and https://theforeman.org/security.html

Doesn't this create a kind of endless loop? security page referencing to itself? 😉

Will wait for further replys but will already create a PR, which you can judge...

**Comment by evgeni** [comment]
I've opened https://github.com/theforeman/theforeman.org/pull/2048 and I hope I avoided the endless loop in the wording ;-)
