### ISSUE TITLE
Incorrect rpm name

### ISSUE THREAD

**Issue by NathanTindle** [theforeman/theforeman.org#2068]
When following documentation to configure openSCAP I have found the ansible client role package is named incorrectly

currently 

ansible-foreman_scap_client

Package correct name is

ansiblerole-foreman_scap_client

See https://theforeman.org/plugins/foreman_openscap/1.0/index.html

2.3.2 Ansible
Please read [section](https://theforeman.org/plugins/foreman_openscap/1.0/index.html#4.6.1Authenticatingclients) about client authentication if running Foreman without Katello. Recommended way is to install the packaged version from our repositories:

yum -y install ansible-foreman_scap_client

**Comment by ekohl** [comment]
Thanks for the report. I've updated it a bit in #2071, but also created https://github.com/theforeman/puppet-foreman_proxy/pull/802 so the installer can manage the package instead as a better long term solution.
