### ISSUE TITLE
foreman-installer smartproxy error (undefined method 'find')

### ISSUE THREAD

**Issue by eternaltyro** [theforeman/theforeman.org#223]
I get the following error on Ubuntu Trusty 

> [ERROR 2014-06-04 08:09:59 verbose]  /Stage[main]/Foreman_proxy::Register/Foreman_smartproxy[homesystem.rabbithole]: Could not evaluate: undefined method `find' for #String:0x000000051f5928

There are no other errors and the web dashboard seems to work fine. Clues?

**Comment by ares** [comment]
Please report issue on our issue tracker at http://projects.theforeman.org under right project (Smart-Proxy) and upload complete log from the run. You can use github account for logging in. I'm closing this issue, thanks for the report.
