### ISSUE TITLE
License.md missing

### ISSUE THREAD

**Issue by kyzh** [theforeman/theforeman.org#27]
Apart of the contribution.md, there is no mention of any license.
Is it implied that the theforeman.org is also part of the project and should be treated as GPL too ?
Would it be possible to have a license.md with the relevant license in it ?

**Comment by domcleal** [comment]
@kyzh thanks for spotting this!  I've suggested in GH-28 that we use a CC licence for the task, it's better suited to content and have started a thread on foreman-dev in case there's discussion.
