### ISSUE TITLE
Smart-proxy templates feature not documented

### ISSUE THREAD

**Issue by dLobatog** [theforeman/theforeman.org#289]
http://theforeman.org/manuals/1.7/index.html#4.3SmartProxies should include a subsection about templates handling with an example configuration file and so forth. @dustints would you mind to do it since you wrote the feature?

**Comment by stbenjam** [comment]
This should get updated and then opened against 1.8:
  https://github.com/theforeman/theforeman.org/pull/313

Without the separate http/https settings, I don't even think it's worth adding to the 1.7 manual.

**Comment by domcleal** [comment]
Yeah, I agree with the reason.  I think the 1.7 patch is woefully incomplete, it hadn't been completed.  Things look in better shape for 1.8.

**Comment by domcleal** [comment]
Fixed in #468.
