### ISSUE TITLE
Foreman passes incorrect case sensitivity on "Run Puppet" to mco 

### ISSUE THREAD

**Issue by tek0011** [theforeman/theforeman.org#299]
When using the "Run Puppet" button on hosts in Foreman, under the mco provider, it will send the command to mco with a lower case fqdn and will then fail to find it:

mco ping:
Ultralisk                                time=104.35 ms

Command as it comes in from foreman:
`[root@puppet etc]# /usr/bin/mco puppet runonce -I ultralisk
No request sent, we did not discover any nodes.`

but if you manually run it with the correct case it works fine.

**Comment by domcleal** [comment]
This repository is about the website, if you want to file a bug against Foreman or the smart proxy, http://projects.theforeman.org/projects/smart-proxy/issues/new would be the correct place.
