### ISSUE TITLE
CoreOS provisioning

### ISSUE THREAD

**Issue by domcleal** [theforeman/theforeman.org#368]
Foreman 1.8 supports provisioning of CoreOS, which should be added to the website and manual.

http://projects.theforeman.org/issues/7652
https://github.com/theforeman/community-templates/tree/master/coreos

**Comment by dLobatog** [comment]
I guess this doesn't cover it , https://github.com/theforeman/theforeman.org/commit/f76e5b476042f1804b68df357730a73759a05641 do you want a special section for it in the manual?

**Comment by domcleal** [comment]
Yeah, I think we should have a section on it and other OSes, to be honest.  Mostly to tell people which templates are relevant, the relevant mirror/installation media etc.

**Comment by mmoll** [comment]
@johscheuer could you have a look on this?

**Comment by johscheuer** [comment]
So there should be a ne section `OSes` in the [manual](http://theforeman.org/manuals/1.11/index.html)? I will have a look for CoreOS and submit a PR (hopefully till end of the week).

**Comment by domcleal** [comment]
We've got a section now at http://theforeman.org/manuals/1.11/index.html#4.4.8OSSpecificNotes, so it would just need a CoreOS sub-section.  Thanks @johscheuer!

**Comment by GregSutcliffe** [comment]
Looks like this should've been closed ages ago ;)
