### ISSUE TITLE
Docs for Discovery Plugin Smart Proxies section 2.2 

### ISSUE THREAD

**Issue by symgryph** [theforeman/theforeman.org#503]
I did finally notice the 'optional' section after logging into IRC, but perhaps in section 2.1 you can say 'you can now discover hosts skip section 2.2 unless you have a locked down environment.'.

**Comment by lzap** [comment]
What exactly is wrong here? Can you perhaps make a PR with the suggested change so we can discuss your proposal directly? Thanks!

**Comment by symgryph** [comment]
I think it was more my following directions blindly and missing that it was  optional. It wasn't clear why I would need to install smart proxy plugin.

**Comment by lzap** [comment]
Ok then.
