### ISSUE TITLE
Global status and substatus descriptions

### ISSUE THREAD

**Issue by domcleal** [theforeman/theforeman.org#511]
A new section, perhaps 4.9 Monitoring in 4. General Foreman should be added to describe the global statuses and substatuses feature added in Foreman 1.10.

It should show that each host has multiple statuses shown on its own host page, and this is combined into a global status shown on the host list.  The APIs show this too, with individual statuses and a global status.

**Comment by ares** [comment]
this should be added by https://github.com/theforeman/theforeman.org/pull/515, I didn't mention API there since I didn't find it anywhere in manual except a generic chapter

anyway if you want me to describe something in more details, please comment in the PR, I'm closing this
