### ISSUE TITLE
Blog and the Homepage

### ISSUE THREAD

**Issue by roidelapluie** [theforeman/theforeman.org#518]
There should at least be a link to the blog on the foreman home page. It would be beter to have links to the X(=3?) latest articles as well.

**Comment by domcleal** [comment]
Latest articles could replace the contents of the latest_news include.

**Comment by GregSutcliffe** [comment]
+1 for a blog link on the home page (as per my various other PRs which keep getting shot down). I'm not sure about the latest articles though, I think that might clutter the page. latest_news is only in the footer, which probably isn't too helpful, as our page is quite long - I don't know how many people scroll to the end vs using the links at the top.

**Comment by dLobatog** [comment]
https://github.com/theforeman/theforeman.org/pull/513
