### ISSUE TITLE
Prefered Ruby version

### ISSUE THREAD

**Issue by Moncky** [theforeman/theforeman.org#523]
The contribute.md and handbook.md should indicate a ruby version for developers to use.

Not all gems are created equal and whilst AFAIK the latest version _should_ be ok, until we know it is we should have a note saying we know that all the gems compile fine against ruby version 2.x.x

A side note, as there doesn't appear to be a specified version I am not suggesting, to be clear, that we indicate a version to be used, just that a known version will work to make setting up a dev environment as easy and as hurdle free as possible for new contributors.

**Comment by GregSutcliffe** [comment]
In general, you can see what versions we currently test at http://ci.theforeman.org/view/Foreman%20pipeline/job/test_develop/ - perhaps we should add a note about that? We could say these versions should work fine, older is not supported, and please raise issues if you're testing with a newer ruby?

**Comment by Moncky** [comment]
Its probably just as good to link to that page with a brief explanation, that way you don't have to worry about keeping the page upto date.  I don't particuarly think there is an issue in pointing to a Jenkins page.  Even if a new developer is unfamiliar with Jenkins they will be at somepoint I guess.

I've added a note to the contribute.md, on reflection I'm not sure there is any benefit in replicating on the handbook.md page.  

PR https://github.com/theforeman/theforeman.org/pull/525
