### ISSUE TITLE
gh-pages deprecates rdiscount markdown

### ISSUE THREAD

**Issue by mmoll** [theforeman/theforeman.org#542]
Per GitHub:

You are currently using the 'rdiscount' Markdown engine, which will not be supported on GitHub Pages after May 1st. At that time, your site will use 'kramdown' for markdown rendering instead. To suppress this warning, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.

**Comment by mmoll** [comment]
related issues to watch:
- [x] github/pages-gem#205
- [x] gettalong/kramdown#234
- [x] jneen/rouge/issues/187

IMHO these must get resolved first. However, if the github-pages gem drops rdiscount before that, it's easy for us to pull it in again, as we're not building on GitHub.

**Comment by gettalong** [comment]
gettalong/kramdown#234 is now fixed

**Comment by mmoll** [comment]
@gettalong Danke!
