### ISSUE TITLE
invalid page and per_page parameter in API in foreman 1.11

### ISSUE THREAD

**Issue by lsioctl** [theforeman/theforeman.org#598]
Hi,

I'm testing the API of my fresh foreman 1.11 installation.

The page parameter, for exemple there 

http://theforeman.org/api/1.11/

does not work as documented at least for puppetclasses. 

Documentation says it want a string

```
page
optional    

paginate results

Validations:

    Must be String

```

and foreman api wants a integer.

e.g  if I search asking no pagination 

```
url = '/api/v2/puppetclasses?search=m&page=false'
```

I've got :

```
invalid value for Integer(): "false"'
```

page parameter is in fact the page name

per_page doesn't work, I've got 20 results whatever the integer I send.

Tell me if I could help.

Regards,

**Comment by domcleal** [comment]
Please file a bug against the API if `per_page` doesn't work on one of the APIs, I don't think this is a website or documentation issue.  See http://projects.theforeman.org/projects/foreman/issues/new.
