### ISSUE TITLE
Missing SSL certs/keys for facts on multiple puppetmasters with no ENC

### ISSUE THREAD

**Issue by blkperl** [theforeman/theforeman.org#73]
```
_includes/manuals/1.2/3.5.5_importing_facts.md
```

Refers to this script https://github.com/theforeman/puppet-foreman/blob/283619064fbde0275235535b19c53da249357035/files/push_facts.rb which was deleted.

The script needs to be updated to include the CA file and certs or the docs need to be updated to explain how to do it without the script.

``` ruby
$foreman_ssl_ca = "/var/lib/puppet/ssl/certs/ca.pem"
$foreman_ssl_cert = "/var/lib/puppet/ssl/certs/<fqdn>.pem" 
$foreman_ssl_key = "/var/lib/puppet/ssl/private_keys/<fqdn>.pem"
```

And at the http part

``` ruby
http.ca_file = $foreman_ssl_ca
http.cert = OpenSSL::X509::Certificate.new(File.read($foreman_ssl_cert))
http.key  = OpenSSL::PKey::RSA.new(File.read($foreman_ssl_key), nil)
```

Thanks,
William

**Comment by domcleal** [comment]
Yeah, the docs shouldn't be referring to that script any more.  We merged its functionality into the ENC node.rb script via the `--push-facts` argument so they shared a common code base, but clearly forgot to update the docs.

**Comment by domcleal** [comment]
Closing this issue as we've since updated the docs to refer to node.rb for pushing facts, which supports SSL.
