### ISSUE TITLE
Foreman Mirrors

### ISSUE THREAD

**Issue by elJoeyJojo** [theforeman/theforeman.org#741]
Hello,

I'm fairly new at Foreman and I want to be able to provision linux VMs using a local repo and I'm not sure how to do that. At the moment Foreman is working fine but it goes online to get the ISO/installation files and it takes a bit, it would probably make more sense to have the ISO/installation files locally and have the provisioning done locally. Not sure how can I do this, but I do know I can just create a new Installation Media but just not sure about the permissions, the files that must be there and any other things I might need. Please help me and thank you very much.

Joey

**Comment by mmoll** [comment]
You can create mirrors in any way, the OS provides, e.g. rsync yum/apt repos of CentOS/Debian or loopback-mount ISO-images of SLES/RHEL on a local webserver. Then point the URL of the Installation medium in Foreman to your mirror.

If it's "only" about a slow uplink, a caching proxy can help, personally I use apt-cacher-ng which was built for that special purpose.

Also, please don't use this issue tracker for support questions, we have the IRC channel and the foreman-users mailinglist for such questions, there's also the possibility of asking on serverfault.

**Comment by dLobatog** [comment]
If you want to make local mirrors of your OSs - http://katello.org/ is a wonderful option which does that by linking Pulp repos to Foreman provisioning
