### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by lachlansimpson** [theforeman/theforeman.org#868]
On the upgrade page of the nightly version, under Step 1 Backup

If Katello is running on a Virtual Machine, we reccomend to take a snapshot prior to upgrading. Otherwise, take a backup of the relevant databases by following the instructions here.

reccomend should be recommend

**Comment by mmoll** [comment]
@datakid Could you open a pull request?

**Comment by lachlansimpson** [comment]
Done https://github.com/theforeman/theforeman.org/pull/875

**Comment by mmoll** [comment]
thanks!
