### ISSUE TITLE
Foreman 1.17 manual

### ISSUE THREAD

**Issue by xprazak2** [theforeman/theforeman.org#974]
Usual stuff:

* [x] Headline features
   ~~Headline feature screencasts~~
* [x] Itemised release notes
* [x] Foreman setting changes
* [ ] Smart proxy setting changes
* [ ] Installer options refresh
* [x] Contributors list
* [ ] Translator contributors
* [ ] Installer module release notes
* [x] API documentation per README
* [x] List all new deprecation warnings
* [x] Update Puppet compatibility matrix

1.17 specifics:

* [x] #21011 default role creation skips auditing
* [x] Last release supporting APIv1 (https://github.com/theforeman/foreman/pull/5068)

**Comment by GregSutcliffe** [comment]
Can we close this now that 1.17 is out @xprazak2? Or is it still tracking important stuff?

**Comment by xprazak2** [comment]
I think we can close now.
